[project]
name = "example_project"
version = "0.1.0"
dependencies = [
    "ipykernel>=7.1.0",
    "nbformat>=5.10.4",
    "networkx>=3.4.2",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
]
